// analysis-engine.js - Real Aggregation + Real Claude-Backed Reasoning
//
// Scout/Analyst work (this file) stays deterministic JavaScript: every number
// here is computed directly from the loaded CSV. Strategy/Action reasoning
// (insights/recommendations copy) comes from an async call to
// /.netlify/functions/analyze, which forwards ONLY the aggregated JSON below
// (never the raw CSV) to the Anthropic API. If that call fails, the UI shows
// the computed aggregates with an honest banner instead of any fabricated text.

const analysisEngine = (function() {
    'use strict';

    let selectedAnalysis = null;
    let chart = null;
    let processingStartTime = 0;

    const CORE_V1_COLUMNS = [
        'product_id', 'product_name', 'category', 'style', 'fit', 'fabric', 'color',
        'price', 'views', 'cart_adds', 'purchases', 'revenue'
    ];
    const V2_MARKER_COLUMNS = ['normalized_fabric', 'normalized_color', 'region', 'customer_age_group'];
    const ATTRIBUTE_DIMENSIONS = ['fabric', 'color', 'fit', 'style', 'category'];
    const TOP_N_PER_DIMENSION = 15;
    const SMALL_SAMPLE_MIN_COUNT = 5;
    const SMALL_SAMPLE_MIN_VIEWS = 500;

    // ---- Selection / UI wiring -------------------------------------------------

    function selectAnalysis(evt, type) {
        selectedAnalysis = type;

        document.querySelectorAll('.option-card').forEach(card => {
            card.classList.remove('selected');
        });
        if (evt && evt.target) {
            evt.target.closest('.option-card').classList.add('selected');
        }

        uiController.showNotification(`${type.charAt(0).toUpperCase() + type.slice(1)} analysis selected`);
    }

    function enableAnalysis() {
        const executeBtn = document.getElementById('executeBtn');
        if (executeBtn) {
            executeBtn.disabled = false;
        }
    }

    // ---- Execution --------------------------------------------------------------

    async function executeAnalysis() {
        const data = dataLoader.getData();

        if (!data || data.length === 0) {
            uiController.showNotification('Please load data first', 'error');
            return;
        }

        if (!selectedAnalysis) {
            uiController.showNotification('Please select an analysis type', 'error');
            return;
        }

        processingStartTime = Date.now();
        hideAiBanner();
        uiController.showProcessingOverlay();

        try {
            // Stage 1-2: real, synchronous aggregation (this is genuinely fast).
            updateProcessingStatus('Ingesting and validating catalog data...');
            activateProcessStage(1);
            const results = analyzeProductData(data);
            activateProcessStage(2);

            // Stage 3: hand the aggregates (never the raw CSV) to the Strategy Agent.
            updateProcessingStatus('Strategy Agent analyzing via Claude...');
            activateProcessStage(3);
            if (typeof agenticAI !== 'undefined') {
                agenticAI.onAnalysisStart(selectedAnalysis, results);
            }

            let apiResponse = null;
            let apiError = null;
            try {
                apiResponse = await fetchAnalysis(selectedAnalysis, results);
            } catch (err) {
                apiError = err;
            }

            activateProcessStage(4);
            updateProcessingStatus(apiError ? 'AI insights unavailable...' : 'Rendering insights and recommendations...');

            const processingTime = ((Date.now() - processingStartTime) / 1000).toFixed(1);
            uiController.updateElement('processingTime', processingTime + 's');

            if (apiError) {
                console.error('Analyze function error:', apiError);
                displayFallback(results, apiError.message);
                if (typeof agenticAI !== 'undefined') {
                    agenticAI.onAnalysisError(apiError.message);
                }
                uiController.showNotification('AI insights unavailable — showing computed metrics only.', 'error');
            } else {
                displayResults(results, apiResponse);
                if (typeof agenticAI !== 'undefined') {
                    agenticAI.onAnalysisComplete(apiResponse, results);
                }
                uiController.showNotification('Analysis complete. Insights generated by Claude from your real aggregates.');
            }

            const resultsSection = document.getElementById('resultsSection');
            if (resultsSection) {
                resultsSection.style.display = 'block';
                resultsSection.scrollIntoView({ behavior: 'smooth' });
            }
        } finally {
            uiController.hideProcessingOverlay();
            deactivateProcessStages();
        }
    }

    function updateProcessingStatus(status) {
        const statusEl = document.getElementById('processStatus');
        if (statusEl) {
            statusEl.textContent = status;
        }
    }

    function activateProcessStage(stage) {
        const stageEl = document.querySelector(`.process-stage[data-stage="${stage}"]`);
        if (stageEl) {
            stageEl.classList.add('active');
        }
    }

    function deactivateProcessStages() {
        document.querySelectorAll('.process-stage').forEach(stage => {
            stage.classList.remove('active');
        });
    }

    // ---- Real aggregation (Scout + Analyst work) --------------------------------

    function detectSchema(data) {
        const keys = Object.keys(data[0] || {});
        const hasV2Markers = V2_MARKER_COLUMNS.some(col => keys.includes(col));
        const missingCore = CORE_V1_COLUMNS.filter(col => !keys.includes(col));

        let schema = 'unknown';
        if (missingCore.length === 0) {
            schema = hasV2Markers ? 'v2' : 'v1';
        }

        return { schema, missingCore, columnCount: keys.length };
    }

    function toNumber(value) {
        const n = parseFloat(value);
        return Number.isFinite(n) ? n : 0;
    }

    function analyzeProductData(data) {
        const { schema, missingCore } = detectSchema(data);

        const attributeAggregates = {};
        ATTRIBUTE_DIMENSIONS.forEach(dim => {
            attributeAggregates[dim] = aggregateDimension(data, dim);
        });

        const catalogTotals = data.reduce((acc, product) => {
            acc.revenue += toNumber(product.revenue);
            acc.views += toNumber(product.views);
            acc.cartAdds += toNumber(product.cart_adds);
            acc.purchases += toNumber(product.purchases);
            acc.returnRateSum += toNumber(product.return_rate);
            acc.ratingSum += toNumber(product.customer_rating);
            return acc;
        }, { revenue: 0, views: 0, cartAdds: 0, purchases: 0, returnRateSum: 0, ratingSum: 0 });

        const catalogSummary = {
            schema,
            missingColumns: missingCore,
            totalProducts: data.length,
            totalRevenue: catalogTotals.revenue,
            totalViews: catalogTotals.views,
            totalCartAdds: catalogTotals.cartAdds,
            totalPurchases: catalogTotals.purchases,
            overallConversionRate: catalogTotals.views > 0 ? catalogTotals.purchases / catalogTotals.views : null,
            avgReturnRate: data.length > 0 ? catalogTotals.returnRateSum / data.length : null,
            avgRating: data.length > 0 ? catalogTotals.ratingSum / data.length : null,
        };

        const funnelStats = {
            totalViews: catalogTotals.views,
            totalCartAdds: catalogTotals.cartAdds,
            totalPurchases: catalogTotals.purchases,
            viewToCartRate: catalogTotals.views > 0 ? catalogTotals.cartAdds / catalogTotals.views : null,
            cartToPurchaseRate: catalogTotals.cartAdds > 0 ? catalogTotals.purchases / catalogTotals.cartAdds : null,
            overallConversionRate: catalogSummary.overallConversionRate,
        };

        const anomalies = computeAnomalies(attributeAggregates);

        // Revenue concentration: share of total revenue held by the top 3 fabric values.
        const topFabrics = (attributeAggregates.fabric || []).slice(0, 3);
        const top3Share = catalogTotals.revenue > 0
            ? topFabrics.reduce((sum, f) => sum + f.revenue, 0) / catalogTotals.revenue
            : 0;

        const topAttributeEntry = findTopRevenueAttribute(attributeAggregates);

        return {
            catalogSummary,
            attributeAggregates,
            funnelStats,
            anomalies,
            topAttribute: topAttributeEntry ? topAttributeEntry.value : 'N/A',
            topAttributeDimension: topAttributeEntry ? topAttributeEntry.dimension : null,
            conversionRate: catalogSummary.overallConversionRate,
            revenueImpact: catalogTotals.revenue,
            revenueConcentrationTop3: top3Share,
        };
    }

    function aggregateDimension(data, dim) {
        const groups = {};

        data.forEach(product => {
            const key = product[dim];
            if (!key) return;

            if (!groups[key]) {
                groups[key] = { value: key, count: 0, revenue: 0, views: 0, cartAdds: 0, purchases: 0, returnRateSum: 0, ratingSum: 0 };
            }
            const g = groups[key];
            g.count++;
            g.revenue += toNumber(product.revenue);
            g.views += toNumber(product.views);
            g.cartAdds += toNumber(product.cart_adds);
            g.purchases += toNumber(product.purchases);
            g.returnRateSum += toNumber(product.return_rate);
            g.ratingSum += toNumber(product.customer_rating);
        });

        const totalRevenue = Object.values(groups).reduce((sum, g) => sum + g.revenue, 0);

        const rows = Object.values(groups).map(g => ({
            value: g.value,
            count: g.count,
            revenue: g.revenue,
            revenueShare: totalRevenue > 0 ? g.revenue / totalRevenue : 0,
            conversionRate: g.views > 0 ? g.purchases / g.views : null,
            cartToPurchaseRate: g.cartAdds > 0 ? g.purchases / g.cartAdds : null,
            avgReturnRate: g.count > 0 ? g.returnRateSum / g.count : null,
            avgRating: g.count > 0 ? g.ratingSum / g.count : null,
            unitVelocity: g.count > 0 ? g.purchases / g.count : null,
            views: g.views,
            purchases: g.purchases,
        }));

        rows.sort((a, b) => b.revenue - a.revenue);
        return rows.slice(0, TOP_N_PER_DIMENSION);
    }

    function findTopRevenueAttribute(attributeAggregates) {
        let best = null;
        Object.keys(attributeAggregates).forEach(dim => {
            const top = attributeAggregates[dim][0];
            if (top && (!best || top.revenue > best.revenue)) {
                best = { dimension: dim, value: top.value, revenue: top.revenue };
            }
        });
        return best;
    }

    // Real statistical outlier + small-sample detection (no fabricated confidence scores).
    function computeAnomalies(attributeAggregates) {
        const anomalies = [];

        Object.keys(attributeAggregates).forEach(dim => {
            const rows = attributeAggregates[dim];
            const conversionRates = rows.map(r => r.conversionRate).filter(v => v !== null);
            const returnRates = rows.map(r => r.avgReturnRate).filter(v => v !== null);

            const convStats = meanAndStdDev(conversionRates);
            const returnStats = meanAndStdDev(returnRates);

            rows.forEach(row => {
                if (row.conversionRate !== null && convStats.stdDev > 0) {
                    const deviation = (row.conversionRate - convStats.mean) / convStats.stdDev;
                    if (Math.abs(deviation) > 1) {
                        anomalies.push({
                            dimension: dim,
                            value: row.value,
                            metric: 'conversionRate',
                            catalogMean: convStats.mean,
                            stdDev: convStats.stdDev,
                            deviation,
                            direction: deviation > 0 ? 'above' : 'below',
                            n: row.count,
                            views: row.views,
                            flag: 'outlier',
                        });
                    }
                }
                if (row.avgReturnRate !== null && returnStats.stdDev > 0) {
                    const deviation = (row.avgReturnRate - returnStats.mean) / returnStats.stdDev;
                    if (Math.abs(deviation) > 1) {
                        anomalies.push({
                            dimension: dim,
                            value: row.value,
                            metric: 'returnRate',
                            catalogMean: returnStats.mean,
                            stdDev: returnStats.stdDev,
                            deviation,
                            direction: deviation > 0 ? 'above' : 'below',
                            n: row.count,
                            views: row.views,
                            flag: 'outlier',
                        });
                    }
                }
                if (row.count < SMALL_SAMPLE_MIN_COUNT || row.views < SMALL_SAMPLE_MIN_VIEWS) {
                    anomalies.push({
                        dimension: dim,
                        value: row.value,
                        metric: 'sampleSize',
                        n: row.count,
                        views: row.views,
                        flag: 'small_sample',
                    });
                }
            });
        });

        return anomalies.slice(0, 40);
    }

    function meanAndStdDev(values) {
        if (!values.length) return { mean: 0, stdDev: 0 };
        const mean = values.reduce((a, b) => a + b, 0) / values.length;
        const variance = values.reduce((a, b) => a + (b - mean) ** 2, 0) / values.length;
        return { mean, stdDev: Math.sqrt(variance) };
    }

    // ---- Payload construction + the one real network call -----------------------

    function buildPayload(analysisType, results) {
        let attributeAggregates = results.attributeAggregates;

        let payload = {
            analysisType,
            catalogSummary: results.catalogSummary,
            attributeAggregates,
            funnelStats: results.funnelStats,
            anomalies: results.anomalies,
        };

        // Safety trim: keep the payload well under the function's 100KB hard cap
        // (and comfortably under the ~50KB target) by shrinking per-dimension rows.
        let size = new Blob([JSON.stringify(payload)]).size;
        let topN = TOP_N_PER_DIMENSION;
        while (size > 50 * 1024 && topN > 3) {
            topN -= 3;
            const trimmed = {};
            Object.keys(attributeAggregates).forEach(dim => {
                trimmed[dim] = attributeAggregates[dim].slice(0, topN);
            });
            payload = { ...payload, attributeAggregates: trimmed, anomalies: payload.anomalies.slice(0, 20) };
            size = new Blob([JSON.stringify(payload)]).size;
        }

        return payload;
    }

    async function fetchAnalysis(analysisType, results) {
        const payload = buildPayload(analysisType, results);

        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 12000);

        try {
            const res = await fetch('/.netlify/functions/analyze', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload),
                signal: controller.signal,
            });

            const body = await res.json().catch(() => ({}));

            if (!res.ok) {
                throw new Error(body.error || `Analysis request failed (HTTP ${res.status})`);
            }

            return body;
        } finally {
            clearTimeout(timeout);
        }
    }

    // ---- Rendering ----------------------------------------------------------------

    function formatPercent(value, digits = 1) {
        return value === null || value === undefined ? 'n/a' : (value * 100).toFixed(digits) + '%';
    }

    function displayResults(results, apiResponse) {
        renderMetrics(results);

        const recContainer = document.getElementById('recommendationsList');
        if (recContainer) {
            const recs = (apiResponse && apiResponse.recommendations) || [];
            recContainer.innerHTML = recs.length
                ? recs.map(rec => `
                    <div class="recommendation-item">
                        <h4>${escapeHtml(rec.action || 'Recommendation')}</h4>
                        <p>${escapeHtml(rec.rationale || '')}</p>
                        <small style="color: var(--primary); font-weight: 600;">${escapeHtml(rec.evidence || '')}</small>
                    </div>
                `).join('')
                : '<p>Claude did not return any recommendations for this data.</p>';
        }

        const insightsContainer = document.getElementById('insightsGrid');
        if (insightsContainer) {
            const insights = (apiResponse && apiResponse.insights) || [];
            insightsContainer.innerHTML = insights.length
                ? insights.map(insight => `
                    <div class="insight-item">
                        <div class="insight-value">${escapeHtml(insight.title || '')}</div>
                        <div class="insight-label">${escapeHtml(insight.detail || '')}</div>
                        <small style="color: var(--success); font-weight: 500;">${escapeHtml(insight.evidence || '')}</small>
                    </div>
                `).join('')
                : '<p>Claude did not return any insights for this data.</p>';
        }

        createAttributeChart(results.attributeAggregates);
    }

    // Honest fallback: no AI copy, just the real computed aggregates.
    function displayFallback(results, errorMessage) {
        showAiBanner(`AI insights unavailable (${errorMessage || 'request failed'}) — showing computed metrics only.`);
        renderMetrics(results);

        const recContainer = document.getElementById('recommendationsList');
        if (recContainer) {
            recContainer.innerHTML = '<p>AI-generated recommendations are unavailable right now. The computed attribute metrics below are still real.</p>';
        }

        const insightsContainer = document.getElementById('insightsGrid');
        if (insightsContainer) {
            const topRows = Object.keys(results.attributeAggregates).flatMap(dim =>
                results.attributeAggregates[dim].slice(0, 1).map(row => ({ dim, row }))
            );
            insightsContainer.innerHTML = topRows.map(({ dim, row }) => `
                <div class="insight-item">
                    <div class="insight-value">${escapeHtml(row.value)}</div>
                    <div class="insight-label">Top ${escapeHtml(dim)} by revenue</div>
                    <small>$${Math.round(row.revenue).toLocaleString()} · n=${row.count} · conv ${formatPercent(row.conversionRate)}</small>
                </div>
            `).join('');
        }

        createAttributeChart(results.attributeAggregates);
    }

    function renderMetrics(results) {
        uiController.updateElement('topAttribute', results.topAttribute);
        uiController.updateElement('conversionRate', formatPercent(results.conversionRate));
        uiController.updateElement('revenueImpact', '$' + (results.revenueImpact / 1000000).toFixed(1) + 'M');
        uiController.updateElement('inventoryOptimization', formatPercent(results.revenueConcentrationTop3, 0));

        const changeEls = document.querySelectorAll('.metric-change');
        const changeText = [
            `top ${results.topAttributeDimension || 'attribute'} by revenue`,
            `n=${results.catalogSummary.totalProducts} products`,
            `$${Math.round(results.revenueImpact).toLocaleString()} total`,
            'top 3 fabrics by revenue',
        ];
        changeEls.forEach((el, i) => {
            el.textContent = changeText[i] || '';
            el.classList.remove('positive');
        });
    }

    function showAiBanner(message) {
        const banner = document.getElementById('aiStatusBanner');
        if (banner) {
            banner.textContent = message;
            banner.style.display = 'block';
        }
    }

    function hideAiBanner() {
        const banner = document.getElementById('aiStatusBanner');
        if (banner) {
            banner.style.display = 'none';
        }
    }

    function escapeHtml(str) {
        const div = document.createElement('div');
        div.textContent = String(str == null ? '' : str);
        return div.innerHTML;
    }

    function createAttributeChart(attributeAggregates) {
        const ctx = document.getElementById('attrCanvas');
        if (!ctx) return;

        if (chart) {
            chart.destroy();
        }

        const rows = (attributeAggregates.fabric && attributeAggregates.fabric.length)
            ? attributeAggregates.fabric
            : (Object.values(attributeAggregates).find(r => r.length) || []);

        const labels = rows.slice(0, 8).map(r => r.value);
        const data = rows.slice(0, 8).map(r => (r.revenue / 1000).toFixed(0));

        chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Revenue ($K)',
                    data: data,
                    backgroundColor: 'rgba(20, 110, 180, 0.8)',
                    borderColor: '#146eb4',
                    borderWidth: 2,
                    borderRadius: 8
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        callbacks: {
                            label: function(context) {
                                return 'Revenue: $' + context.parsed.y + 'K';
                            }
                        }
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        grid: { color: 'rgba(0, 0, 0, 0.05)' },
                        ticks: { callback: function(value) { return '$' + value + 'K'; } }
                    },
                    x: { grid: { display: false } }
                }
            }
        });
    }

    return {
        selectAnalysis,
        enableAnalysis,
        executeAnalysis,
        analyzeProductData,
        detectSchema
    };
})();
